### PR TITLE
1.1.6

### PR DESCRIPTION
**Pull request by grawk**

### CODE REVIEW

**Comment by grawk** [comment]
Silly PR. just the minor bump to package.json...

**Comment by aredridel** [comment]
:+1: 

This is always the kind of change I did on master -- `npm version patch && git push origin master --tags && npm publish`

**Comment by grawk** [comment]
wow. how did my merge get up above your :+1: ?!

**Comment by grawk** [comment]
(I'll do that in the future)

**Comment by aredridel** [comment]
You did it before I +1ed it ;-)

**Comment by grawk** [comment]
inconceivable!

**Pull request merged**
