### PR TITLE
Refactor.makara builder2

### PR DESCRIPTION
**Pull request by grawk**
use makara-builder interface introduced here: https://github.com/krakenjs/makara-builder/pull/4

This pulls up the spundle and directory creation from the "writer" method and into makara-builder. Removes repeated code from this module and any other "makara-*" modules.

### CODE REVIEW

**Comment by subeeshcbabu-zz** [comment]
Don't have a lot of context about this change, however wondering, `makara-writer-amd` module is no longer used?

**Comment by grawk** [comment]
`makara-writer-amd` was originally created in order to share code between this module and `construx-makara-amdify`. But with the refactor of `makara-builder`, the shared method was so small (3 lines) as to not really need to be its own module.

**Comment by subeeshcbabu-zz** [comment]
Gotcha. 
Changes look 👍

**Comment by skoranga** [comment]
👍

**Pull request merged**
