### PR TITLE
Use standard define

### PR DESCRIPTION
**Pull request by TheIronDev**
This approach seems to make it easier to use this module for normal AMD projects.

### CODE REVIEW

**Comment by TheIronDev** [comment]
Thinking  about this some more...

**Comment by aredridel** [comment]
Mmm, yeah. The name it defines is important -- which gets loaded is up to the app, and you can either require looking up the locale and requiring the right bundle everywhere, or you can use a single name, and centralize that logic and have it preload it in the app's boot up code.

**Comment by xjamundx** [comment]
@aredridel is there some way to use the named define without a double `require()` wrap in the project? @TheIronDeveloper and I were struggling with this and ended up with something like:

``` js
require([ '../' + userLang + '/_languagepack.js'], function() {
    require(['_languagepack'], function (languagePack) {
```

We're using babel so we're hoping to get it down to something that we can directly `import` in a single line and I'm not quite sure how with the current setup...though probably we just need to keep playing with it.

**Comment by aredridel** [comment]
Yes. try `<script src='/{lang}/_languagepack.js'></script>`.

**Comment by aredridel** [comment]
(It'd also be quite possible to make them not share a name and require them with a dynamic require. all good options.)

**Comment by xjamundx** [comment]
index.html

``` html
<script data-main="/js/app" src="/components/requirejs/require.js"></script>
<script src="/en-US/_languagepack.js"></script>
```

app.js

``` js
import React from 'react';
import ReactIntlMixin from 'react-intl';
import languagePack from '_languagepack';
```

tasks/requirejs.js

``` js
exclude: ['_languagepack'],
paths: {
     '_languagepack': '../components/react/react' // this path can be to anywhere, it's excluded, but needed
}
```

thanks!

**Comment by aredridel** [comment]
Sure thing!

**Pull request closed without merging**
