### PR TITLE
add appRoot and buildRoot options

### LINKED ISSUE #2: Additional Options
A few options might make this easier to work with:
- `outputDir` (right now it's just ./build/` but I'd love to give this it's own folder)
- `locale` it might be nice to be able to limit to a single locale (say in a some kind of development mode)

Any thoughts on if these would be wanted?

### PR DESCRIPTION
**Pull request by xjamundx**
Fixes #2

### CODE REVIEW

**Comment by xjamundx** [comment]
Currently everything goes into `.build/en-US` I want them to go into `.build/js/template-bundles/en-US`...
- I think you're right the `.` is probably not relative to the right / obvious thing. It should probably be relative to `appRoot`.
- `appRoot` was the name before, I just moved it into the `options` object. It refers to the root where the `locales` directory will be found.

This may not be needed if I end up going a different route, let's chat tomorrow if we can!

**Comment by aredridel** [comment]
Hm. Why do you want it in such a deep directory?

**Comment by aredridel** [comment]
Hm. Why do you want it in such a deep directory?

**Comment by aredridel** [comment]
[branch will pass if you rebase on current master]

**Pull request closed without merging**
